//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tesstrterrr
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TistirovanieeEntities : DbContext
    {
        public TistirovanieeEntities()
            : base("name=TistirovanieeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Вопрос_> Вопрос_ { get; set; }
        public virtual DbSet<Дисциплины_> Дисциплины_ { get; set; }
        public virtual DbSet<История_> История_ { get; set; }
        public virtual DbSet<Пользователь_> Пользователь_ { get; set; }
        public virtual DbSet<Тест_> Тест_ { get; set; }
    }
}
