//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tesstrterrr
{
    using System;
    using System.Collections.Generic;
    
    public partial class История_
    {
        public int Номер { get; set; }
        public string Логин { get; set; }
        public Nullable<int> Номер_теста { get; set; }
        public string Результат { get; set; }
        public Nullable<int> Кол__Баллов { get; set; }
        public Nullable<System.TimeSpan> Время { get; set; }
        public Nullable<System.DateTime> Дата { get; set; }
    
        public virtual Пользователь_ Пользователь_ { get; set; }
        public virtual Тест_ Тест_ { get; set; }
    }
}
